title: Portfolio - Abdelhalim Zouggagh
description: Portfolio de Abdelhalim Zouggagh en Génie Électrique et Informatique Industrielle
baseurl: "" # Si tu utilises un sous-dossier pour ton GitHub Pages, renseigne-le ici
url: "https://<ton-utilisateur>.github.io" # Remplace par ton URL GitHub Pages
theme: jekyll-theme-material

# Permet de générer automatiquement le menu de navigation
nav:
  - title: "Accueil"
    url: "index.md"
  - title: "A propos de moi"
    url: "A_propos_de_moi.md"
  - title: "Référentiel des Compétences"
    url: "referenciel.md"
  - title: "Projets"
    children:
      - title: "Semestre 1"
        children:
          - title: "Station de pompage"
            url: "concevoir_station_pompage.md"
          - title: "Robot Suiveur de Ligne"
            url: "concevoir_robot_suiveur.md"
      - title: "Semestre 2"
        children:
          - title: "Moteur de drone"
            url: "concevoir_moteur_drone.md"
          - title: "Snake"
            url: "concevoir_sae_snake.md"
  - title: "Mon expérience personnel"
    children:
      - title: "Projets réalisés"
        url: "projet_realiser.md"
      - title: "Compétences acquises"
        url: "competence_aquise.md"
  - title: "Contact"
    url: "contact.md"

# Paramètres supplémentaires pour les fonctionnalités de Jekyll
markdown: kramdown
permalink: /:title/


extra_css:
  - css/extra.css
  
extra_javascript:
  - https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&display=swap
